export const ItemType = {
	None: 0,
	Clothes: 1,
	Weapons: 2,
	MeleeWeapons: 3,
	Ammo: 4,
	Alco: 5,
	Eat: 6,
	Water: 7,
	Modification: 8,
	Cases: 9,
}

export const ItemId = {
	Debug: 0,
	HealthKit: 1,
	GasCan: 2,
	Crisps: 3,
	Beer: 4,
	Pizza: 5,
	Burger: 6,
	HotDog: 7,
	Sandwich: 8,
	eCola: 9,
	Sprunk: 10,
	Lockpick: 11,
	BagWithMoney: 12,
	Material: 13,
	Drugs: 14,
	BagWithDrill: 15,
	ArmyLockpick: 16,
	Pocket: 17,
	Cuffs: 18,
	CarKey: 19,
	RusDrink1: 20,
	RusDrink2: 21,
	RusDrink3: 22,
	YakDrink1: 23,
	YakDrink2: 24,
	YakDrink3: 25,
	LcnDrink1: 26,
	LcnDrink2: 27,
	LcnDrink3: 28,
	ArmDrink1: 29,
	ArmDrink2: 30,
	ArmDrink3: 31,
	Present: 40,
	KeyRing: 41,
	Pistol: 100,
	CombatPistol: 101,
	Pistol50: 102,
	SNSPistol: 103,
	HeavyPistol: 104,
	VintagePistol: 105,
	MarksmanPistol: 106,
	Revolver: 107,
	APPistol: 108,
	StunGun: 109,
	FlareGun: 110,
	DoubleAction: 111,
	PistolMk2: 112,
	SNSPistolMk2: 113,
	RevolverMk2: 114,
	MicroSMG: 115,
	MachinePistol: 116,
	SMG: 117,
	AssaultSMG: 118,
	CombatPDW: 119,
	MG: 120,
	CombatMG: 121,
	Gusenberg: 122,
	MiniSMG: 123,
	SMGMk2: 124,
	CombatMGMk2: 125,
	AssaultRifle: 126,
	CarbineRifle: 127,
	AdvancedRifle: 128,
	SpecialCarbine: 129,
	BullpupRifle: 130,
	CompactRifle: 131,
	AssaultRifleMk2: 132,
	CarbineRifleMk2: 133,
	SpecialCarbineMk2: 134,
	BullpupRifleMk2: 135,
	SniperRifle: 136,
	HeavySniper: 137,
	MarksmanRifle: 138,
	HeavySniperMk2: 139,
	MarksmanRifleMk2: 140,
	PumpShotgun: 141,
	SawnOffShotgun: 142,
	BullpupShotgun: 143,
	AssaultShotgun: 144,
	Musket: 145,
	HeavyShotgun: 146,
	DoubleBarrelShotgun: 147,
	SweeperShotgun: 148,
	PumpShotgunMk2: 149,
	RayPistol: 150,
	CeramicPistol: 151,
	NavyRevolver: 152,
	RayCarbine: 153,
	GrenadeLauncher: 154,
	RPG: 155,
	Minigun: 156,
	Firework: 157,
	Railgun: 158,
	HomingLauncher: 159,
	GrenadeLauncherSmoke: 160,
	CompactGrenadeLauncher: 161,
	Widowmaker: 162,
	Knife: 180,
	Nightstick: 181,
	Hammer: 182,
	Bat: 183,
	Crowbar: 184,
	GolfClub: 185,
	Bottle: 186,
	Dagger: 187,
	Hatchet: 188,
	KnuckleDuster: 189,
	Machete: 190,
	Flashlight: 191,
	SwitchBlade: 192,
	PoolCue: 193,
	Wrench: 194,
	BattleAxe: 195,
	PistolAmmo: 200,
	SMGAmmo: 201,
	RiflesAmmo: 202,
	SniperAmmo: 203,
	ShotgunsAmmo: 204,
	Snowball: 205,
	cVarmod: 206,
	cClip: 207,
	cSuppressor: 208,
	cScope: 209,
	cMuzzlebrake: 210,
	cBarrel: 211,
	cFlashlight: 212,
	cGrip: 213,
	cCamo: 214,
	HalloweenCoin: 215,
	Firework1: 216,
	Firework2: 217,
	Firework3: 218,
	Firework4: 219,
	CarCoupon: 220,
	MerryChristmasCoin: 221,
	Bear: 222,
	Note: 223,
	LoveNote: 224,
	Vape: 225,
	Rose: 226,
	Barbell: 227,
	Binoculars: 228,
	Bong: 229,
	Umbrella: 230,
	Camera: 231,
	Microphone: 232,
	Guitar: 233,
	Pickaxe1: 234,
	Pickaxe2: 235,
	Pickaxe3: 236,
	Coal: 237,
	Iron: 238,
	Gold: 239,
	Sulfur: 240,
	Emerald: 241,
	Ruby: 242,
	Radio: 243,
	WorkAxe: 244,
	WoodOak: 245,
	WoodMaple: 246,
	WoodPine: 247,
	Boombox: 248,
	Hookah: 249,
	Case0: 250,
	Case1: 251,
	Case2: 252,
	Case3: 253,
	Case4: 254,
	Case5: 255,
	Case6: 256,
	Case7: 257,
	Case8: 258,
	Case9: 259,
	Case10: 260,
	Case11: 261,
	Case12: 262,
	Ball: 263,
	SummerCoin: 264,
	Case13: 265,
	MilitaryRifle: 266,
	CandyCane: 267,
	Case14: 268,
	Qr: 269,
	QrFake: 270,
	SimCard: 271,
	VehicleNumber: 272,
	Bint: 273,
	Cocaine: 274,
	Rub100: 275,
	Rub200: 276,
	Rub500: 277,
	Rub1000: 278,
	RadioInterceptor: 279,
	Epinephrine: 280,
	Case15: 281,
	Case16: 282,
	Case17: 283,
	Case18: 284,
	Case19: 285,
	Case20: 286,
	Case21: 287,
	AppleCoin: 288,
	Fire: 289,
	Matras: 290,
	Tent: 291,
	Lezhak: 292,
	Towel: 293,
	Flag: 294,
	Barrell: 295,
	Surf: 296,
	Vedro: 297,
	Flagstok: 298,
	Tenttwo: 299,
	Polotence: 300,
	Beachbag: 301,
	Zontik: 302,
	Zontiktwo: 303,
	Zontikthree: 304,
	Closedzontik: 305,
	Vball: 306,
	Bball: 307,
	Boomboxxx: 308,
	Table: 309,
	Tabletwo: 310,
	Tablethree: 311,
	Tablefour: 312,
	Chair: 313,
	Chairtwo: 314,
	Chaierthree: 315,
	Chaierfour: 316,
	Chairtable: 317,
	Korzina: 318,
	Light: 319,
	Alco: 320,
	Alcotwo: 321,
	Alcothree: 322,
	Alcofour: 323,
	Cocktail: 324,
	Cocktailtwo: 325,
	Fruit: 326,
	Fruittwo: 327,
	Packet: 328,
	Buter: 329,
	Patatoes: 330,
	Coffee: 331,
	Podnosfood: 332,
	Bbqtwo: 333,
	Bbq: 334,
	Vaza: 335,
	Flagwtokk: 336,
	Flagau: 337,
	Flagbr: 338,
	Flagch: 339,
	Flagcz: 340,
	Flageng: 341,
	Flageu: 342,
	Flagfr: 343,
	Flagger: 344,
	Flagire: 345,
	Flagisr: 346,
	Flagit: 347,
	Flagjam: 348,
	Flagjap: 349,
	Flagmex: 350,
	Flagnet: 351,
	Flagnig: 352,
	Flagnorw: 353,
	Flagpol: 354,
	Flagrus: 355,
	Flagbel: 356,
	Flagscot: 357,
	Flagscr: 358,
	Flagslovak: 359,
	Flagslov: 360,
	Flagsou: 361,
	Flagspain: 362,
	Flagswede: 363,
	Flagswitz: 364,
	Flagturk: 365,
	Flaguk: 366,
	Flagus: 367,
	Flagwales: 368,
	Flagfin: 369,
	Flowerrr: 370,
	Konus: 371,
	Konuss: 372,
	Otboynik1: 373,
	Otboynik2: 374,
	Dontcross: 375,
	Stop: 376,
	NetProezda: 377,
	Kpp: 378,
	Zabor1: 379,
	Zabor2: 380,
	Airlight: 381,
	Camera1: 382,
	Camera2: 383,
	TacticalRifle: 384,
	PrecisionRifle: 385,
	CombatShotgun: 386,
	HeavyRifle: 387,
	NeonStick: 388,
	GlowStick: 389,
	Giftcoin: 390,
	CombatRifle: 391,
	Glock: 392,
	Bracelets: -15,
	Watches: -14,
	Glasses: -13,
	Hat: -12,
	Top: -11,
	Decals: -10,
	BodyArmor: -9,
	Undershit: -8,
	Jewelry: -7,
	Feet: -6,
	Bag: -5,
	Leg: -4,
	Gloves: -3,
	Ears: -2,
	Mask: -1
}

export const itemsInfo = {
	[ItemId.Mask]: {"Name":"Mask","Description":"Helps to hide your identity, but also serves as a decoration. Can be torn off by a police officer.","Icon":"inv-item-mask","Type":"Clothing","Stack":1,"functionType":1},
	[ItemId.Gloves]: {"Name":"Gloves","Description":"Will keep you warm on a cold winter day.","Icon":"inv-item-glove","Type":"Clothing","Stack":1,"functionType":1},
	[ItemId.Ears]: {"Name":"Headphones","Description":".","Icon":"inv-item-ears","Type":"Clothing","Stack":1,"functionType":1},
	[ItemId.Leg]: {"Name":"Pants","Description":"They won't let you freeze.","Icon":"inv-item-shorts","Type":"Clothing","Stack":1,"functionType":1},
	[ItemId.Bag]: {"Name":"Bag","Description":"Allows you to carry any items inside.","Icon":"inv-item-backpack","Type":"Clothing","Stack":1,"functionType":1},
	[ItemId.Feet]: {"Name":"Footwear","Description":"A modern style that will never let you down.","Icon":"inv-item-sneakers","Type":"Clothing","Stack":1,"functionType":1},
	[ItemId.Jewelry]: {"Name":"Accessory","Description":"Allows you to improve your character's appearance.","Icon":"inv-item-necklace","Type":"Clothing","Stack":1,"functionType":1},
	[ItemId.Undershit]: {"Name":"Undershirt","Description":"Can be worn under outerwear, gives your character a stylish look.","Icon":"inv-item-shirt","Type":"Clothing","Stack":1,"functionType":1},
	[ItemId.BodyArmor]: {"Name":"Body Armor","Description":"Serves as protection for the character, able to absorb 100 damage before it breaks.","Icon":"inv-item-armor","Type":"Clothing","Stack":1,"functionType":1},
	[ItemId.Decals]: {"Name":"Decals","Description":"Allows you to improve your character's appearance.","Icon":"inv-item-clock","Type":"Clothing","Stack":1,"functionType":1},
	[ItemId.Top]: {"Name":"Top/Jacket","Description":"Can be worn over an undershirt, gives your character a stylish look.","Icon":"inv-item-jacket","Type":"Clothing","Stack":1,"functionType":1},
	[ItemId.Hat]: {"Name":"Headwear","Description":"Will save you from sunstroke on a hot day.","Icon":"inv-item-cap","Type":"Clothing","Stack":1,"functionType":1},
	[ItemId.Glasses]: {"Name":"Glasses","Description":"Will protect you from the sun on the sunniest day.","Icon":"inv-item-glasses","Type":"Clothing","Stack":1,"functionType":1},
	[ItemId.Bracelets]: {"Name":"Bracelet","Description":"Allows you to improve your character's appearance.","Icon":"inv-item-bracelet","Type":"Clothing","Stack":1,"functionType":1},
	[ItemId.Watches]: {"Name":"Watch","Description":"Shows the status of your character.","Icon":"inv-item-clock","Type":"Clothing","Stack":1,"functionType":1},
	[ItemId.Debug]: {"Name":"None","Description":"","Icon":"","Type":"","Stack":0,"functionType":0},
	[ItemId.BagWithDrill]: {"Name":"Bag with Drill","Description":"Used to break into the vault.","Icon":"inv-item-Bag-drill","Type":"Other","Stack":1,"functionType":0},
	[ItemId.GasCan]: {"Name":"Gas Can","Description":"Can be used to refuel a vehicle.","Icon":"inv-item-gasoline","Type":"Tools","Stack":2,"functionType":0},
	[ItemId.Crisps]: {"Name":"Chips","Description":"A snack, restores 30% health.","Icon":"inv-item-Chips","Type":"Food","Stack":4,"functionType":6},
	[ItemId.Beer]: {"Name":"Beer","Description":"A cold one for the road!","Icon":"inv-item-beer","Type":"Water","Stack":5,"functionType":7},
	[ItemId.Pizza]: {"Name":"Pizza","Description":"Mmm... Pizza... Restores 30% health.","Icon":"inv-item-pizza","Type":"Food","Stack":3,"functionType":6},
	[ItemId.Burger]: {"Name":"Burger","Description":"A bun with a patty, restores 30% health.","Icon":"inv-item-burger","Type":"Food","Stack":4,"functionType":6},
	[ItemId.HotDog]: {"Name":"Hot Dog","Description":"A bun with a sausage, restores 30% health.","Icon":"inv-item-hot-dog","Type":"Food","Stack":5,"functionType":6},
	[ItemId.Sandwich]: {"Name":"Sandwich","Description":"A few slices of bread and meat, restores 30% health.","Icon":"inv-item-sandwich","Type":"Food","Stack":7,"functionType":6},
	[ItemId.eCola]: {"Name":"eCola","Description":"A non-alcoholic carbonated drink, restores 10% health.","Icon":"inv-item-eCola","Type":"Water","Stack":5,"functionType":7},
	[ItemId.Sprunk]: {"Name":"Sprunk","Description":"A highly carbonated soft drink, restores 10% health.","Icon":"inv-item-eCola","Type":"Water","Stack":5,"functionType":7},
	[ItemId.Lockpick]: {"Name":"Lockpick","Description":"A tool for opening locks without a key.","Icon":"inv-item-picklock","Type":"Tool","Stack":10,"functionType":0},
	[ItemId.BagWithMoney]: {"Name":"Bag with Money","Description":"You can put all the money in here after robbing a 24/7.","Icon":"inv-item-briefcase","Type":"Other","Stack":1,"functionType":0},
	[ItemId.Material]: {"Name":"Materials","Description":"Needed to create weapons and ammunition.","Icon":"inv-item-fraction","Type":"Other","Stack":4000,"functionType":0},
	[ItemId.Drugs]: {"Name":"Drugs","Description":"This magical tea produces a narcotic effect.","Icon":"inv-item-marijuana","Type":"Other","Stack":50,"functionType":0},
	[ItemId.HealthKit]: {"Name":"First-Aid Kit","Description":"Needed for healing, can be used once every 5 minutes.","Icon":"inv-item-medical-kit","Type":"Other","Stack":10,"functionType":0},
	[ItemId.ArmyLockpick]: {"Name":"Military Lockpick","Description":"A tool for opening the locks of military vehicles.","Icon":"inv-item-picklock","Type":"Tool","Stack":10,"functionType":0},
	[ItemId.Pocket]: {"Name":"Sack","Description":"A regular sack. They say you can put it on someone's head...","Icon":"inv-item-bag","Type":"Tool","Stack":5,"functionType":0},
	[ItemId.Cuffs]: {"Name":"Zip Ties","Description":"Allows you to tie up a person with their hands up.","Icon":"inv-item-stretching","Type":"Tool","Stack":5,"functionType":0},
	[ItemId.CarKey]: {"Name":"Car Keys","Description":"A tool that allows you to lock/unlock and start a car.","Icon":"inv-item-key","Type":"Tool","Stack":1,"functionType":0},
	[ItemId.Present]: {"Name":"Gift","Description":"Contains something interesting! Open it quickly!","Icon":"inv-item-gift","Type":"Tool","Stack":1,"functionType":0},
	[ItemId.KeyRing]: {"Name":"Key Ring","Description":"Gathers all your keys into one large ring and saves space in your pockets!","Icon":"inv-item-key-2","Type":"Tool","Stack":1,"functionType":0},
	[ItemId.RusDrink1]: {"Name":"<On a Lemon Peel>","Description":"An alcoholic drink with notes of lemon, causes an intoxicating effect.","Icon":"inv-item-On-lemon-peel","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.RusDrink2]: {"Name":"<On Lingonberry>","Description":"An alcoholic drink with a light note of lingonberry, causes an intoxicating effect.","Icon":"inv-item-The-cranberries","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.RusDrink3]: {"Name":"<Russian Standard>","Description":"Good old Russian vodka, causes an intoxicating effect.","Icon":"inv-item-Russian-standard","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.YakDrink1]: {"Name":"<Asahi>","Description":"A beer with low malt content, causes an intoxicating effect.","Icon":"inv-item-Asahi","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.YakDrink2]: {"Name":"<Midori>","Description":"A sweet melon liqueur, causes an intoxicating effect.","Icon":"inv-item-Midori","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.YakDrink3]: {"Name":"<Yamazaki>","Description":"A Japanese whiskey, causes an intoxicating effect.","Icon":"inv-item-Yamazaki","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.LcnDrink1]: {"Name":"<Martini Asti>","Description":"A sparkling wine, causes an intoxicating effect.","Icon":"inv-item-Martini-Asti","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.LcnDrink2]: {"Name":"<Sambuca>","Description":"A strong liqueur with a pleasant anise flavor, causes an intoxicating effect.","Icon":"inv-item-Sambuca","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.LcnDrink3]: {"Name":"<Campari>","Description":"A bitter liqueur based on aromatic herbs and fruits.","Icon":"inv-item-Campari","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.ArmDrink1]: {"Name":"<Jivan>","Description":"An Armenian cognac, causes an intoxicating effect.","Icon":"inv-item-alcohol","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.ArmDrink2]: {"Name":"<Ararat>","Description":"An Armenian cognac with fruity-floral notes, causes an intoxicating effect.","Icon":"inv-item-ararat","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.ArmDrink3]: {"Name":"<Noyan Tapan>","Description":"An Armenian wine drink, causes an intoxicating effect.","Icon":"inv-item-Noyan-Tapan","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.Pistol]: {"Name":"Pistol","Description":"Standard pistol, magazine holds 12 rounds.","Icon":"inv-item-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CombatPistol]: {"Name":"Combat Pistol","Description":"Combat pistol, magazine holds 12 rounds.","Icon":"inv-item-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Pistol50]: {"Name":"Pistol .50","Description":"Powerful .50 caliber pistol, magazine holds 9 rounds.","Icon":"inv-item-Pistol-50","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.SNSPistol]: {"Name":"SNS Pistol","Description":"Pocket-sized .25 caliber pistol, magazine holds 6 rounds.","Icon":"inv-item-SNS-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.HeavyPistol]: {"Name":"Heavy Pistol","Description":"Heavy pistol, magazine holds 18 rounds.","Icon":"inv-item-Heavy-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.VintagePistol]: {"Name":"Vintage Pistol","Description":"Vintage pistol, magazine holds 7 rounds.","Icon":"inv-item-Vintage-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.MarksmanPistol]: {"Name":"Marksman Pistol","Description":"Marksman pistol, holds 1 round.","Icon":"inv-item-Marksman-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Revolver]: {"Name":"Revolver","Description":"Revolver, holds 6 rounds.","Icon":"inv-item-Heavy-Revolver","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.APPistol]: {"Name":"AP Pistol","Description":"Armor-piercing pistol, magazine holds 18 rounds.","Icon":"inv-item-AP-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.StunGun]: {"Name":"Stun Gun","Description":"An electroshock weapon, holds 1 charge.","Icon":"inv-item-Stun-Gun","Type":"Melee Weapon","Stack":1,"functionType":2},
	[ItemId.FlareGun]: {"Name":"Flare Gun","Description":"A signal pistol.","Icon":"inv-item-Flare-Gun","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.DoubleAction]: {"Name":"Double Action Revolver","Description":"Self-cocking revolver, holds 6 rounds.","Icon":"inv-item-Double-Action-Revolver","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.PistolMk2]: {"Name":"Pistol Mk2","Description":"An improved version of the standard pistol, magazine holds 12 rounds.","Icon":"inv-item-Pistol-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.SNSPistolMk2]: {"Name":"SNS Pistol Mk2","Description":"An improved version of the pocket pistol, magazine holds 6 rounds.","Icon":"inv-item-SNS-Pistol-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.RevolverMk2]: {"Name":"Heavy Revolver Mk2","Description":"An improved version of the standard revolver, holds 6 rounds.","Icon":"inv-item-Heavy-Revolver-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.MicroSMG]: {"Name":"Micro SMG","Description":"Compact submachine gun, magazine holds 16 rounds.","Icon":"inv-item-Micro-SMG","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.MachinePistol]: {"Name":"Machine Pistol","Description":"Automatic pistol, magazine holds 12 rounds.","Icon":"inv-item-Machine-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.SMG]: {"Name":"SMG","Description":"Submachine gun, magazine holds 30 rounds.","Icon":"inv-item-SMG","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.AssaultSMG]: {"Name":"Assault SMG","Description":"Assault submachine gun, magazine holds 30 rounds.","Icon":"inv-item-Assault-SMG","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CombatPDW]: {"Name":"Combat PDW","Description":"Compact assault rifle, magazine holds 30 rounds.","Icon":"inv-item-Combat-PDW","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.MG]: {"Name":"MG","Description":"Heavy machine gun, magazine holds 54 rounds.","Icon":"inv-item-MG","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CombatMG]: {"Name":"Combat MG","Description":"Special purpose machine gun, magazine holds 100 rounds.","Icon":"inv-item-Combat-MG","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Gusenberg]: {"Name":"Gusenberg Sweeper","Description":"Submachine gun, magazine holds 30 rounds.","Icon":"inv-item-Gusenberg-Sweeper","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.MiniSMG]: {"Name":"Mini SMG","Description":"Compact submachine gun, magazine holds 20 rounds.","Icon":"inv-item-Mini-SMG","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.SMGMk2]: {"Name":"SMG Mk2","Description":"Improved submachine gun, magazine holds 30 rounds.","Icon":"inv-item-SMG-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CombatMGMk2]: {"Name":"Combat MG Mk2","Description":"Upgraded general-purpose machine gun, holds 100 rounds.","Icon":"inv-item-Combat-MG-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.AssaultRifle]: {"Name":"Assault Rifle","Description":"Assault rifle, magazine holds 30 rounds.","Icon":"inv-item-Assault-Rifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CarbineRifle]: {"Name":"Carbine Rifle","Description":"American semi-automatic rifle, magazine holds 30 rounds.","Icon":"inv-item-Carbine-Rifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.AdvancedRifle]: {"Name":"Advanced Rifle","Description":"Advanced assault rifle, magazine holds 30 rounds.","Icon":"inv-item-Advanced-Rifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.SpecialCarbine]: {"Name":"Special Carbine","Description":"Assault rifle with less recoil, magazine holds 30 rounds.","Icon":"inv-item-Special-Carbine","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.BullpupRifle]: {"Name":"Bullpup Rifle","Description":"Chinese assault rifle, magazine holds 30 rounds.","Icon":"inv-item-Bullpup-Rifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CompactRifle]: {"Name":"Compact Rifle","Description":"Shortened rifle, magazine holds 30 rounds.","Icon":"inv-item-Compact-Rifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.AssaultRifleMk2]: {"Name":"Assault Rifle Mk2","Description":"Improved assault rifle, magazine holds 30 rounds.","Icon":"inv-item-Assault-Rifle-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CarbineRifleMk2]: {"Name":"Carbine Rifle Mk2","Description":"Improved semi-automatic rifle, magazine holds 30 rounds.","Icon":"inv-item-Carbine-Rifle-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.SpecialCarbineMk2]: {"Name":"Special Carbine Mk2","Description":"Improved assault rifle with a shorter barrel, magazine holds 30 rounds.","Icon":"inv-item-Special-Carbine-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.BullpupRifleMk2]: {"Name":"Bullpup Rifle Mk2","Description":"Improved Chinese assault rifle, magazine holds 30 rounds.","Icon":"inv-item-Bullpup-Rifle-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.MilitaryRifle]: {"Name":"Military Rifle","Description":"Advanced assault rifle, magazine holds 30 rounds.","Icon":"inv-item-militaryrifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.SniperRifle]: {"Name":"Sniper Rifle","Description":"Sniper rifle, magazine holds 10 rounds.","Icon":"inv-item-Sniper-Rifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.HeavySniper]: {"Name":"Heavy Sniper","Description":"High-caliber sniper rifle, magazine holds 6 rounds.","Icon":"inv-item-Heavy-Sniper","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.MarksmanRifle]: {"Name":"Marksman Rifle","Description":"Marksman sniper rifle, magazine holds 8 rounds.","Icon":"inv-item-Marksman-Rifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.HeavySniperMk2]: {"Name":"Heavy Sniper Mk2","Description":"Improved high-caliber sniper rifle, magazine holds 6 rounds.","Icon":"inv-item-Heavy-Sniper-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.MarksmanRifleMk2]: {"Name":"Marksman Rifle Mk2","Description":"Improved marksman sniper rifle, magazine holds 8 rounds.","Icon":"inv-item-Marksman-Rifle-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.PumpShotgun]: {"Name":"Pump Shotgun","Description":"Tactical combat pump shotgun, holds 8 shells.","Icon":"inv-item-Pump-Shotgun","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.SawnOffShotgun]: {"Name":"Sawn-Off Shotgun","Description":"Sawn-off shotgun, holds 8 shells.","Icon":"inv-item-Sawed-Off-Shotgun","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.BullpupShotgun]: {"Name":"Bullpup Shotgun","Description":"Pump shotgun, holds 14 shells.","Icon":"inv-item-Bullpup-Shotgun","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.AssaultShotgun]: {"Name":"Assault Shotgun","Description":"Assault shotgun, holds 8 shells.","Icon":"inv-item-Assault-Shotgun","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Musket]: {"Name":"Musket","Description":"Handheld firearm, holds 1 round.","Icon":"inv-item-Musket","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.HeavyShotgun]: {"Name":"Heavy Shotgun","Description":"Heavy six-shot shotgun, holds 6 shells.","Icon":"inv-item-Heavy-Shotgun","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.DoubleBarrelShotgun]: {"Name":"Double Barrel Shotgun","Description":"Double-barrel shotgun, holds 2 shells.","Icon":"inv-item-Double-Barrel-Shotgun","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.SweeperShotgun]: {"Name":"Sweeper Shotgun","Description":"Compact rapid-fire shotgun, holds 10 shells.","Icon":"inv-item-Sweeper-Shotgun","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.PumpShotgunMk2]: {"Name":"Pump Shotgun Mk2","Description":"Improved pump shotgun, holds 8 shells.","Icon":"inv-item-Pump-Shotgun-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.RayPistol]: {"Name":"Up-n-Atomizer","Description":"Futuristic pistol resembling an alien gun, requires no ammunition.","Icon":"inv-item-Vintage-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CeramicPistol]: {"Name":"Ceramic Pistol","Description":"Ceramic pistol, magazine holds 12 rounds.","Icon":"inv-item-Combat-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.NavyRevolver]: {"Name":"Navy Revolver","Description":"Army revolver, holds 6 rounds.","Icon":"inv-item-Heavy-Revolver-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.RayCarbine]: {"Name":"Unholy Hellbringer","Description":"Futuristic plasma rifle with an unusual appearance.","Icon":"NEEDTEXT","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.GrenadeLauncher]: {"Name":"Grenade Launcher","Description":"Lightweight semi-automatic grenade launcher, holds up to 10 rounds.","Icon":"","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.RPG]: {"Name":"RPG","Description":"Handheld anti-tank rocket launcher, holds 1 rocket.","Icon":"NEEDTEXT","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Minigun]: {"Name":"Minigun","Description":"6-barrel machine gun with a very high rate of fire, holds 595 rounds.","Icon":"NEEDTEXT","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Firework]: {"Name":"Firework Launcher","Description":"A launcher for fireworks, helps to lift the mood or celebrate a holiday.","Icon":"NEEDTEXT","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Railgun]: {"Name":"Railgun","Description":"A heavy rail weapon with high damage, holds up to 20 rounds.","Icon":"NEEDTEXT","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.HomingLauncher]: {"Name":"Homing Launcher","Description":"A rocket launcher with infrared homing, holds 1 rocket.","Icon":"NEEDTEXT","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.GrenadeLauncherSmoke]: {"Name":"Smoke Grenade Launcher","Description":"A light grenade launcher that fires smoke grenades instead of regular ones.","Icon":"NEEDTEXT","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CompactGrenadeLauncher]: {"Name":"Compact Grenade Launcher","Description":"A compact grenade launcher that holds only 1 round.","Icon":"NEEDTEXT","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Widowmaker]: {"Name":"Widowmaker","Description":"A futuristic plasma machine gun, holds up to 9999 rounds.","Icon":"NEEDTEXT","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Knife]: {"Name":"Knife","Description":"A sharp knife that you can cut yourself with.","Icon":"inv-item-Knife","Type":"Melee Weapon","Stack":1,"functionType":3},
	[ItemId.Nightstick]: {"Name":"Nightstick","Description":"Found a lawbreaker? Time to use the nightstick.","Icon":"inv-item-Nightstick","Type":"Melee Weapon","Stack":1,"functionType":3},
	[ItemId.Hammer]: {"Name":"Hammer","Description":"A hammer will help you with household chores.","Icon":"inv-item-Hammer","Type":"Melee Weapon","Stack":1,"functionType":3},
	[ItemId.Bat]: {"Name":"Baseball Bat","Description":"A bat is great for playing baseball.","Icon":"inv-item-Baseball-Bat","Type":"Melee Weapon","Stack":1,"functionType":3},
	[ItemId.Crowbar]: {"Name":"Crowbar","Description":"The crowbar is one of the most popular tools.","Icon":"inv-item-crowbar","Type":"Melee Weapon","Stack":1,"functionType":3},
	[ItemId.GolfClub]: {"Name":"Golf Club","Description":"Will let you have a great time on the golf course.","Icon":"inv-item-Golf-Club","Type":"Melee Weapon","Stack":1,"functionType":3},
	[ItemId.Bottle]: {"Name":"Broken Bottle","Description":"A shiv made from a bottle.","Icon":"inv-item-Broken-Bottle","Type":"Melee Weapon","Stack":1,"functionType":3},
	[ItemId.Dagger]: {"Name":"Dagger","Description":"Very suitable for collectors of rare weapons.","Icon":"inv-item-Antique-Cavalry-Dagger","Type":"Melee Weapon","Stack":1,"functionType":3},
	[ItemId.Hatchet]: {"Name":"Hatchet","Description":"Need to chop some wood? The hatchet is an excellent helper.","Icon":"inv-item-Hatchet","Type":"Melee Weapon","Stack":1,"functionType":3},
	[ItemId.KnuckleDuster]: {"Name":"Brass Knuckles","Description":"An excellent helper in street fights.","Icon":"inv-item-Brass-Knuckles","Type":"Melee Weapon","Stack":1,"functionType":3},
	[ItemId.Machete]: {"Name":"Machete","Description":"One of the most effective weapons for survival in the wild jungle. ","Icon":"inv-item-Machete","Type":"Melee Weapon","Stack":1,"functionType":3},
	[ItemId.Flashlight]: {"Name":"Flashlight","Description":"A bright light that will help you if you get lost in a dark forest.","Icon":"inv-item-Flashlight","Type":"Melee Weapon","Stack":1,"functionType":3},
	[ItemId.SwitchBlade]: {"Name":"Switchblade","Description":"A folding knife that will help you solve many problems.","Icon":"inv-item-Switchblade","Type":"Melee Weapon","Stack":1,"functionType":3},
	[ItemId.PoolCue]: {"Name":"Pool Cue","Description":"Perfect for playing billiards.","Icon":"inv-item-Pool-Cue","Type":"Melee Weapon","Stack":1,"functionType":3},
	[ItemId.Wrench]: {"Name":"Pipe Wrench","Description":"The wrench is your truest helper if something breaks.","Icon":"inv-item-Pipe-Wrench","Type":"Melee Weapon","Stack":1,"functionType":3},
	[ItemId.BattleAxe]: {"Name":"Battle Axe","Description":"Need to chop up some enemies? The axe is an excellent helper for that.","Icon":"inv-item-Battle-Axe","Type":"Melee Weapon","Stack":1,"functionType":3},
	[ItemId.PistolAmmo]: {"Name":"Pistol Ammo","Description":"This ammo is perfect for your pistol.","Icon":"inv-item-ammo-pistol","Type":"Ammo","Stack":100,"functionType":4},
	[ItemId.RiflesAmmo]: {"Name":"Rifle Ammo","Description":"This ammo is perfect for assault rifles.","Icon":"inv-item-ammo-average","Type":"Ammo","Stack":250,"functionType":4},
	[ItemId.ShotgunsAmmo]: {"Name":"Shotgun Shells","Description":"Suitable for any type of shotgun.","Icon":"inv-item-ammo-shotgun","Type":"Ammo","Stack":50,"functionType":4},
	[ItemId.SMGAmmo]: {"Name":"SMG Ammo","Description":"Perfect for your submachine gun and other small-caliber weapons.","Icon":"inv-item-ammo-small","Type":"Ammo","Stack":300,"functionType":4},
	[ItemId.SniperAmmo]: {"Name":"Sniper Ammo","Description":"Suitable for all sniper rifles.","Icon":"inv-item-ammo-sniper","Type":"Ammo","Stack":48,"functionType":4},
	[ItemId.Snowball]: {"Name":"Snowball","Description":"Throw it at someone!","Icon":"inv-item-marijuana","Type":"Special","Stack":1,"functionType":2},
	[ItemId.Ball]: {"Name":"Ball","Description":"For playing with your pet.","Icon":"inv-item-ball","Type":"Special","Stack":1,"functionType":2},
	[ItemId.cVarmod]: {"Name":"Weapon Tint","Description":"With this component, you can paint a weapon, making it more visually appealing.","Icon":"inv-item-Varmod","Type":"Special","Stack":1,"functionType":8},
	[ItemId.cClip]: {"Name":"Weapon Magazine","Description":"An improved magazine will expand the maximum ammo capacity of the weapon.","Icon":"inv-item-Clips","Type":"Special","Stack":1,"functionType":8},
	[ItemId.cSuppressor]: {"Name":"Weapon Suppressor","Description":"A suppressor, when installed, muffles the sound of shots and allows for silent kills.","Icon":"inv-item-Suppressors","Type":"Special","Stack":1,"functionType":8},
	[ItemId.cScope]: {"Name":"Weapon Scope","Description":"A scope, when installed, will allow the weapon's owner to aim more precisely at their enemies (Use the mouse wheel).","Icon":"inv-item-Scopes","Type":"Special","Stack":1,"functionType":8},
	[ItemId.cMuzzlebrake]: {"Name":"Weapon Muzzle Brake","Description":"This component reduces weapon recoil.","Icon":"inv-item-Muzzle-Brakes","Type":"Special","Stack":1,"functionType":8},
	[ItemId.cBarrel]: {"Name":"Weapon Barrel","Description":"An improved weapon barrel increases accuracy and damage.","Icon":"inv-item-Barrels","Type":"Special","Stack":1,"functionType":8},
	[ItemId.cFlashlight]: {"Name":"Weapon Flashlight","Description":"A flashlight mounted on a weapon is a great way to find your enemies in the dark (Press E to turn on).","Icon":"inv-item-Flashlights","Type":"Special","Stack":1,"functionType":8},
	[ItemId.cGrip]: {"Name":"Weapon Grip","Description":"An improved weapon grip provides more comfortable shooting.","Icon":"inv-item-Grips","Type":"Special","Stack":1,"functionType":8},
	[ItemId.cCamo]: {"Name":"Weapon Camo","Description":"With a new skin, you can diversify the appearance of your weapon.","Icon":"inv-item-Varmod","Type":"Special","Stack":1,"functionType":8},
	[ItemId.HalloweenCoin]: {"Name":"Halloween 2020 Coin","Description":"A Halloween coin that can be exchanged for special prizes during the event.","Icon":"inv-item-EventCoin","Type":"Special","Stack":999999,"functionType":0},
	[ItemId.Firework1]: {"Name":"Regular Firework","Description":"A beautiful firework.","Icon":"inv-item-Firework1","Type":"Entertainment","Stack":1,"functionType":0},
	[ItemId.Firework2]: {"Name":"Star Firework","Description":"A beautiful star-shaped firework.","Icon":"inv-item-Firework2","Type":"Entertainment","Stack":1,"functionType":0},
	[ItemId.Firework3]: {"Name":"Burst Firework","Description":"A beautiful explosive-burst firework.","Icon":"inv-item-Firework3","Type":"Entertainment","Stack":1,"functionType":0},
	[ItemId.Firework4]: {"Name":"Fountain Firework","Description":"A beautiful fountain-shaped firework.","Icon":"inv-item-Firework4","Type":"Entertainment","Stack":1,"functionType":0},
	[ItemId.CarCoupon]: {"Name":"Car Coupon","Description":"Contains a vehicle that will be delivered to your garage upon activation.","Icon":"inv-item-car","Type":"Coupons","Stack":1,"functionType":0},
	[ItemId.MerryChristmasCoin]: {"Name":"Christmas 2021 Coin","Description":"A Christmas coin that can be exchanged for special prizes during the event.","Icon":"inv-item-EventCoin","Type":"Special","Stack":999999,"functionType":0},
	[ItemId.Bear]: {"Name":"Love Bear","Description":"Give it to someone nice!","Icon":"inv-item-teddy-bear","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Note]: {"Name":"Note","Description":"With a note, you can leave a message, pass a secret, or other important information.","Icon":"inv-item-Note","Type":"Special","Stack":1,"functionType":0},
	[ItemId.LoveNote]: {"Name":"Love Note","Description":"A valentine will help describe your warm feelings for someone.","Icon":"inv-item-LoveNote","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Vape]: {"Name":"Vape","Description":"A puff of juicy vape always lifts the mood.","Icon":"inv-item-Vape","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Rose]: {"Name":"Rose","Description":"A beautiful gift for a loved one!","Icon":"inv-item-rose","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Barbell]: {"Name":"Barbell","Description":"For those who want to work on their physique.","Icon":"inv-item-barbell","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Binoculars]: {"Name":"Binoculars","Description":"Allows you to see objects at a long distance.","Icon":"inv-item-binoculars","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Bong]: {"Name":"Bong","Description":"A handy thing for consuming weed.","Icon":"inv-item-bong","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Umbrella]: {"Name":"Umbrella","Description":"Allows you to take cover from the rain and adds style.","Icon":"inv-item-umbrella","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Camera]: {"Name":"Camera","Description":"Lights... Camera... Action!","Icon":"inv-item-camera","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Microphone]: {"Name":"Microphone","Description":"The item of a true orator.","Icon":"inv-item-microphone","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Guitar]: {"Name":"Guitar","Description":"It's just asking to be played... Play something!","Icon":"inv-item-guitar","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Pickaxe1]: {"Name":"Regular Pickaxe","Description":"With this thing, you can work at the mine.","Icon":"inv-item-pickaxe1","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Pickaxe2]: {"Name":"Reinforced Pickaxe","Description":"With this thing, you can work powerfully at the mine.","Icon":"inv-item-pickaxe2","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Pickaxe3]: {"Name":"Professional Pickaxe","Description":"With this thing, you can work professionally at the mine.","Icon":"inv-item-pickaxe3","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Coal]: {"Name":"Coal","Description":"A resource from the mine.","Icon":"inv-item-coal","Type":"Special","Stack":250,"functionType":0},
	[ItemId.Iron]: {"Name":"Iron Ore","Description":"A resource from the mine.","Icon":"inv-item-iron","Type":"Special","Stack":250,"functionType":0},
	[ItemId.Gold]: {"Name":"Gold Ore","Description":"A resource from the mine.","Icon":"inv-item-gold","Type":"Special","Stack":250,"functionType":0},
	[ItemId.Sulfur]: {"Name":"Sulfur Ore","Description":"A rare resource from the mine.","Icon":"inv-item-sulfur","Type":"Special","Stack":250,"functionType":0},
	[ItemId.Emerald]: {"Name":"Emerald","Description":"An extremely rare resource from the mine.","Icon":"inv-item-emerald","Type":"Special","Stack":250,"functionType":0},
	[ItemId.Ruby]: {"Name":"Ruby","Description":"A very rare resource from the mine.","Icon":"inv-item-ruby","Type":"Special","Stack":250,"functionType":0},
	[ItemId.Radio]: {"Name":"Walkie-Talkie","Description":"With a walkie-talkie, you can communicate with other owners, or even eavesdrop on police or other secret frequencies.","Icon":"hud__icon-walkie-talkie","Type":"Special","Stack":1,"functionType":0},
	[ItemId.WorkAxe]: {"Name":"Work Axe","Description":"A tool for working as a lumberjack.","Icon":"inv-item-workaxe","Type":"Special","Stack":1,"functionType":0},
	[ItemId.WoodOak]: {"Name":"Oak Wood","Description":"Wood.","Icon":"inv-item-woodoak","Type":"Special","Stack":250,"functionType":0},
	[ItemId.WoodMaple]: {"Name":"Maple Wood","Description":"Wood.","Icon":"inv-item-woodmaple","Type":"Special","Stack":250,"functionType":0},
	[ItemId.WoodPine]: {"Name":"Pine Wood","Description":"Wood.","Icon":"inv-item-woodpine","Type":"Special","Stack":250,"functionType":0},
	[ItemId.Boombox]: {"Name":"Boombox","Description":"Allows you to play your own music for people around. Get the party started!","Icon":"inv-item-boombox","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Hookah]: {"Name":"Hookah","Description":"A hookah for a fierce smoke! Double apple and let's fly...","Icon":"inv-item-hookah","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Case0]: {"Name":"Free Daily Case","Description":"A free case, can be obtained after 3 hours of play.","Icon":"inv-item-case0","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case1]: {"Name":"Free Weapon Case","Description":"A free weapon case, can be obtained after 5 hours of play.","Icon":"inv-item-case1","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case2]: {"Name":"Free Vehicle Case","Description":"A free vehicle case, can be obtained after 8 hours of play.","Icon":"inv-item-case2","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case3]: {"Name":"Standard Case","Description":"A standard case with standard prizes.","Icon":"inv-item-case3","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case4]: {"Name":"Strange Case","Description":"A decent case for beginners.","Icon":"inv-item-case4","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case5]: {"Name":"Special Case","Description":"A juicy case, with a chance for a serious profit!","Icon":"inv-item-case5","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case6]: {"Name":"Rare Case","Description":"A case with items and vehicles of higher rarity.","Icon":"inv-item-case6","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case7]: {"Name":"Fierce Case","Description":"A very fierce case. The grand prize is a Bugatti, the fastest car.","Icon":"inv-item-case7","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case8]: {"Name":"Men's Case","Description":"A case with MEN'S clothing from the donation store. Test your luck and be stylish, or sell it and be rich. Or you could even gift it...","Icon":"inv-item-case8","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case9]: {"Name":"Women's Case","Description":"A case with WOMEN'S clothing from the donation store. A great option if you want to give a gift.","Icon":"inv-item-case9","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case10]: {"Name":"Exotic Case","Description":"A case with cars from the Exotic DonateRoom. Donata Redbucksovna approves!","Icon":"inv-item-case10","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case11]: {"Name":"Legendary Case","Description":"All or nothing! Want to risk it and become the owner of the legendary RedAge sweater? Then spin the case!","Icon":"inv-item-case11","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case12]: {"Name":"Interesting Case","Description":"Been wanting a unique car that isn't sold anywhere? The Dodge Charger is in this case!","Icon":"inv-item-case12","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case13]: {"Name":"Helicopter Case","Description":"Love looking down on people? A helicopter is probably perfect for that!","Icon":"inv-item-case13","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case14]: {"Name":"Armored Case","Description":"A cool new case with trendy armored cars!","Icon":"inv-item-case14","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case15]: {"Name":"Exclusive Case","Description":"A cool new case with placeable items!","Icon":"inv-item-case15","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case16]: {"Name":"Snow Case [M]","Description":"An exclusive case from the Battle Pass, containing several clothing sets with an equal drop chance. ","Icon":"inv-item-case16","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case17]: {"Name":"Amethyst Case [M]","Description":"An exclusive case from the Battle Pass, containing several clothing sets with an equal drop chance. ","Icon":"inv-item-case17","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case18]: {"Name":"Holiday Case [M]","Description":"An exclusive case from the Battle Pass, containing several clothing sets with an equal drop chance. ","Icon":"inv-item-case18","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case19]: {"Name":"Snow Case [F]","Description":"An exclusive case from the Battle Pass, containing several clothing sets with an equal drop chance. ","Icon":"inv-item-case19","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case20]: {"Name":"Amethyst Case [F]","Description":"An exclusive case from the Battle Pass, containing several clothing sets with an equal drop chance. ","Icon":"inv-item-case20","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case21]: {"Name":"Holiday Case [F]","Description":"An exclusive case from the Battle Pass, containing several clothing sets with an equal drop chance. ","Icon":"inv-item-case21","Type":"Special","Stack":100,"functionType":9},
	[ItemId.SummerCoin]: {"Name":"Jaguar Coin","Description":"A coin that can be obtained for special prizes during the event. THIS IS NOT A DONATION CURRENCY!","Icon":"inv-item-EventCoin","Type":"Special","Stack":999999,"functionType":0},
	[ItemId.CandyCane]: {"Name":"Candy Cane","Description":"A Christmas candy cane that can be exchanged for special prizes during the event.","Icon":"inv-item-EventCoin","Type":"Special","Stack":999999,"functionType":0},
	[ItemId.Qr]: {"Name":"QR Code","Description":"A QR code containing information about a past illness and/or vaccination. To be presented on demand.","Icon":"inv-item-QR","Type":"Special","Stack":1,"functionType":0},
	[ItemId.QrFake]: {"Name":"QR Code","Description":"A QR code containing information about a past illness and/or vaccination. To be presented on demand.","Icon":"inv-item-QR","Type":"Special","Stack":1,"functionType":0},
	[ItemId.SimCard]: {"Name":"SIM Card","Description":"A SIM card with a phone number. It can be inserted into any modern smartphone to use the cellular network: send SMS, make calls, and more.","Icon":"inv-item-SimCard","Type":"Special","Stack":1,"functionType":0},
	[ItemId.VehicleNumber]: {"Name":"Vehicle License Plate","Description":"A vehicle license plate. You can install it on your car, sell it, or give it to someone!","Icon":"inv-item-SimCard","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Bint]: {"Name":"Bandage","Description":"A bandage that restores 40% health. Can be used once every 3 minutes. ","Icon":"inv-item-SimCard","Type":"Other","Stack":10,"functionType":0},
	[ItemId.Cocaine]: {"Name":"White Powder","Description":"This magical powder induces a narcotic effect.","Icon":"inv-item-SimCard","Type":"Other","Stack":10,"functionType":0},
	[ItemId.Rub100]: {"Name":"100 Rubles","Description":"You can exchange this item for real money with the Project Lead! ","Icon":"inv-item-SimCard","Type":"Other","Stack":1,"functionType":0},
	[ItemId.Rub200]: {"Name":"200 Rubles","Description":"You can exchange this item for real money with the Project Lead! ","Icon":"inv-item-SimCard","Type":"Other","Stack":1,"functionType":0},
	[ItemId.Rub500]: {"Name":"500 Rubles","Description":"You can exchange this item for real money with the Project Lead! ","Icon":"inv-item-SimCard","Type":"Other","Stack":1,"functionType":0},
	[ItemId.Rub1000]: {"Name":"1000 Rubles","Description":"You can exchange this item for real money with the Project Lead!","Icon":"inv-item-SimCard","Type":"Other","Stack":1,"functionType":0},
	[ItemId.RadioInterceptor]: {"Name":"Radio Interceptor","Description":"Allows you to receive data about HeliCrashes.","Icon":"hud__icon-walkie-talkie","Type":"Other","Stack":1,"functionType":0},
	[ItemId.Epinephrine]: {"Name":"Epinephrine","Description":"Needed for treatment, can be used once every 5 minutes.","Icon":"inv-item-medical-kit","Type":"Other","Stack":10,"functionType":0},
	[ItemId.AppleCoin]: {"Name":"Apple Coin","Description":"A summer coin that can be obtained during the event. F for Apple Pay.","Icon":"inv-item-medical-kit","Type":"Other","Stack":999,"functionType":0},
	[ItemId.Fire]: {"Name":"Campfire","Description":"Suitable for evening gatherings, don't get burned!","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Matras]: {"Name":"Inflatable Mattress","Description":"For beach holidays and to avoid drowning.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Tent]: {"Name":"Tent","Description":"For camping, picnics, and a wild night.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Lezhak]: {"Name":"Sun Lounger","Description":"For beach holidays, you can lie down and think about a bright future.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Towel]: {"Name":"Rolled Towel","Description":"For beach holidays.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flag]: {"Name":"Flag","Description":"Russian flag, don't forget to purchase a flagpole.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Barrell]: {"Name":"Barrel","Description":"Suitable for various needs.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Surf]: {"Name":"Surfboard","Description":"For beach holidays.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Vedro]: {"Name":"Bucket","Description":"Suitable for beach holidays.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagstok]: {"Name":"Sprunk Flagpole","Description":"A flagpole with a large Sprunk flag attached.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Tenttwo]: {"Name":"Tent","Description":"For camping, picnics, and a wild night.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Polotence]: {"Name":"Beach Towel","Description":"For beach holidays.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Beachbag]: {"Name":"Beach Bag","Description":"For beach holidays.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Zontik]: {"Name":"Umbrella","Description":"Will protect from the sun and is suitable for beach holidays.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Zontiktwo]: {"Name":"Umbrella","Description":"Will protect from the sun and is suitable for beach holidays.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Zontikthree]: {"Name":"Umbrella","Description":"Will protect from the sun and is suitable for beach holidays.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Closedzontik]: {"Name":"Closed Umbrella","Description":"Won't protect from the sun, but is suitable for beach holidays.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Vball]: {"Name":"Volleyball","Description":"For fun games and beach holidays.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Bball]: {"Name":"Beach Ball","Description":"For fun games and beach holidays.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Boomboxxx]: {"Name":"Boombox","Description":"Suitable for hanging out with friends.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Table]: {"Name":"Table","Description":"Suitable for picnics or general relaxation.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Tabletwo]: {"Name":"Table","Description":"Suitable for picnics or general relaxation.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Tablethree]: {"Name":"Table","Description":"Suitable for picnics or general relaxation.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Tablefour]: {"Name":"Table","Description":"Suitable for picnics or general relaxation.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Chair]: {"Name":"Chair","Description":"Suitable for picnics or general relaxation.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Chairtwo]: {"Name":"Chair","Description":"Suitable for picnics or general relaxation.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Chaierthree]: {"Name":"Chair","Description":"Suitable for picnics or general relaxation.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Chaierfour]: {"Name":"Chair","Description":"Suitable for picnics or general relaxation.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Chairtable]: {"Name":"Table and Chair","Description":"Suitable for picnics or general relaxation.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Korzina]: {"Name":"Basket","Description":"Suitable for picnics or general relaxation.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Light]: {"Name":"Lighting","Description":"Lighting that will be useful in the dark.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Alco]: {"Name":"Bottle of Brandy","Description":"An expensive bottle of brandy for fun and a good night with a girl or guy.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Alcotwo]: {"Name":"Bottle of Cognac","Description":"An expensive bottle of cognac for fun and a good night with a girl or guy.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Alcothree]: {"Name":"Bottle of Tequila","Description":"An expensive bottle of tequila for fun and a good night with a girl or guy.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Alcofour]: {"Name":"Bottle of Beer","Description":"Cheap beer, suitable for hanging out with friends in nature.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Cocktail]: {"Name":"Cocktail","Description":"A mix of citrus fruits and alcohol, perfect for your girlfriend.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Cocktailtwo]: {"Name":"Cocktail","Description":"A mix of citrus fruits and alcohol, perfect for your girlfriend.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Fruit]: {"Name":"Plate of Fruit","Description":"A delicious and fragrant plate of fruit.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Fruittwo]: {"Name":"Plate of Fruit","Description":"A delicious and fragrant plate of fruit.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Packet]: {"Name":"Bag","Description":"Suitable for a picnic.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Buter]: {"Name":"Burger","Description":"Suitable for a picnic.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Patatoes]: {"Name":"French Fries","Description":"Suitable for a picnic.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Coffee]: {"Name":"Hot Coffee","Description":"Suitable for a picnic.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Podnosfood]: {"Name":"Food Tray","Description":"Suitable for a picnic.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Bbqtwo]: {"Name":"BBQ","Description":"Suitable for a picnic or general relaxation.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Bbq]: {"Name":"Large BBQ","Description":"Suitable for a picnic or general relaxation.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flowerrr]: {"Name":"Bouquet of Flowers","Description":"A beautiful bouquet of colorful flowers that your lady will like.","Icon":"prop_snow_flower_02","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Vaza]: {"Name":"Vase with Flowers","Description":"A vase with beautiful white flowers that your lady will like.","Icon":"vw_prop_flowers_vase_01a","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagwtokk]: {"Name":"Flagpole","Description":"Suitable for picnics or general relaxation.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagau]: {"Name":"Flag of Australia","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_australia","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagbr]: {"Name":"Flag of Brazil","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_brazil","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagch]: {"Name":"Flag of China","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_china","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagcz]: {"Name":"Flag of Czech Republic","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_czechrep","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flageng]: {"Name":"Flag of England","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_england","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flageu]: {"Name":"Flag of the European Union","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_eu_yt","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagfin]: {"Name":"Flag of Finland","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_finland","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagfr]: {"Name":"Flag of France","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_france","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagger]: {"Name":"Flag of Germany","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_german_yt","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagire]: {"Name":"Flag of Ireland","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_ireland","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagisr]: {"Name":"Flag of Israel","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_israel","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagit]: {"Name":"Flag of Italy","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_italy","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagjam]: {"Name":"Flag of Jamaica","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_jamaica","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagjap]: {"Name":"Flag of Japan","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_japan_yt","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagmex]: {"Name":"Flag of Mexico","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_mexico_yt","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagnet]: {"Name":"Flag of the Netherlands","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_netherlands","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagnig]: {"Name":"Flag of Nigeria","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_nigeria","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagnorw]: {"Name":"Flag of Norway","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_norway","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagpol]: {"Name":"Flag of Poland","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_poland","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagrus]: {"Name":"Flag of Russia","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_russia_yt","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagbel]: {"Name":"Flag of Belgium","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_belgium","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagscot]: {"Name":"Flag of Scotland","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_scotland_yt","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagscr]: {"Name":"Script Flag","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_script","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagslov]: {"Name":"Flag of Slovakia","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_slovakia","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagslovak]: {"Name":"Flag of Slovenia","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_slovenia","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagsou]: {"Name":"Flag of South Korea","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_southkorea","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagspain]: {"Name":"Flag of Spain","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_spain","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagswede]: {"Name":"Flag of Sweden","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_sweden","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagswitz]: {"Name":"Flag of Switzerland","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_switzerland","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagturk]: {"Name":"Flag of Turkey","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_turkey","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flaguk]: {"Name":"Flag of the United Kingdom","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_uk_yt","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagus]: {"Name":"Flag of America","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_us_yt","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Flagwales]: {"Name":"Flag of Wales","Description":"Medium-sized flag, requires a flagpole for mounting.","Icon":"apa_prop_flag_wales","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Konus]: {"Name":"Cone","Description":"Suitable as a barrier.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Konuss]: {"Name":"Luminous Cone","Description":"Suitable as a barrier.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Otboynik1]: {"Name":"Barrier","Description":"Suitable as a barrier.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Otboynik2]: {"Name":"Barrier","Description":"Suitable as a barrier.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Dontcross]: {"Name":"Roadblock","Description":"Suitable as a barrier.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Stop]: {"Name":"STOP Sign","Description":"Suitable for traffic rules.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.NetProezda]: {"Name":"NO ENTRY Sign","Description":"Suitable for traffic rules.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Zabor1]: {"Name":"Large Fence","Description":"Suitable for a picnic.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Kpp]: {"Name":"Checkpoint Booth","Description":"Suitable for setting up a checkpoint.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Zabor2]: {"Name":"Small Fence","Description":"Suitable as a barrier.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Airlight]: {"Name":"Night Light","Description":"Suitable as a barrier.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Camera1]: {"Name":"CCTV Camera","Description":"Suitable for surveillance.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.Camera2]: {"Name":"CCTV Camera","Description":"Suitable for surveillance.","Icon":"placingprop","Type":"Placeable Items","Stack":1,"functionType":0},
	[ItemId.TacticalRifle]: {"Name":"Tactical Rifle","Description":"Advanced assault rifle, magazine holds 30 rounds.","Icon":"inv-item-militaryrifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.PrecisionRifle]: {"Name":"Precision Rifle","Description":"Advanced sniper rifle, magazine holds 6 rounds.","Icon":"inv-item-militaryrifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CombatShotgun]: {"Name":"Combat Shotgun","Description":"Advanced shotgun, holds 10 shells.","Icon":"inv-item-militaryrifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.HeavyRifle]: {"Name":"Heavy Rifle","Description":"Advanced assault rifle, magazine holds 30 rounds.","Icon":"inv-item-militaryrifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.NeonStick]: {"Name":"Neon Sticks","Description":"Red sticks that you can hold in your hands.","Icon":"inv-item-Assault-Rifle","Type":"Special","Stack":1,"functionType":0},
	[ItemId.GlowStick]: {"Name":"Glow Sticks","Description":"Beautiful glowing sticks that you can hold in your hands.","Icon":"inv-item-Assault-Rifle","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Giftcoin]: {"Name":"Gift","Description":"A gift box that Santa hid for you!","Icon":"inv-item-Assault-Rifle","Type":"Special","Stack":999,"functionType":0},
	[ItemId.CombatRifle]: {"Name":"Combat Rifle","Description":"A rifle that mows down everything in its path.","Icon":"inv-item-Carbine-Rifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Glock]: {"Name":"Banana Glock","Description":"Banana Glock is top-tier.","Icon":"inv-item-Carbine-Rifle","Type":"Weapon","Stack":1,"functionType":2}
}